adsm_dial.in_file ""
adsm_dial.out_file ""
adsm_dial.create 0
adsm_dial.for_main 1
adsm_dial.for_sec 1
adsm_dial.for_which_parts 0
adsm_dial.in_all_views 0
adsm_dial.OutOfPlane 0
adsm_dial.text_type 0
adsm_dial.text_colour 153
adsm_dial.frame_type 0
adsm_dial.line_colour 153
adsm_dial.Angle 0.000000
adsm_dial.ArrowType 17
adsm_dial.ArrowHeight 0.000000
adsm_dial.ArrowLength 0.000000
adsm_dial.height 0.000000
adsm_dial.default_size 20.637500
adsm_dial.mark_nsfs 0
adsm_dial.content_1 0
adsm_dial.flags 0
adsm_dial.mark_use_part_end 0
adsm_dial.ContentString1 "<?xml version="1.0" encoding="UTF-8" standalone="no"?><!DOCTYPE Mark><Mark><MarkPart groupid="0"><Element name="HOLE.DIAMETER" value="" subType="9"><Format font="Arial" color="153" height="3.175" hidden="0" override="1"/></Element></MarkPart><MarkPart groupid="0"><UserText>Ø<Format font="Arial" color="153" height="3.175" hidden="0" override="1"/></UserText></MarkPart></Mark>"
adsm_dial.ContentString2 "<?xml version="1.0" encoding="UTF-8" standalone="no"?><!DOCTYPE Mark><Mark><MarkPart groupid="0"><Element name="SCREW_HOLE_DIAMETER" value="" subType="9"><Format font="Arial" color="153" height="3.175" hidden="0" override="1"/></Element></MarkPart><MarkPart groupid="0"><UserText>Ø<Format font="Arial" color="153" height="3.175" hidden="0" override="1"/></UserText></MarkPart><MarkPart groupid="0"><LineFeed/></MarkPart><MarkPart groupid="0"><Element name="" value="" subType="15"><Format font="Arial" color="153" height="3.175" hidden="0" override="1"/></Element></MarkPart><MarkPart groupid="0"><UserText>-<Format font="Arial" color="153" height="3.175" hidden="0" override="1"/></UserText></MarkPart><MarkPart groupid="0"><Element name="SCREW_DIAMETER" value="" subType="8"><Format font="Arial" color="153" height="3.175" hidden="0" override="1"/></Element></MarkPart><MarkPart groupid="0"><UserText>Øx<Format font="Arial" color="153" height="3.175" hidden="0" override="1"/></UserText></MarkPart><MarkPart groupid="0"><Element name="LENGTH" value="" subType="7"><Format font="Arial" color="153" height="3.175" hidden="0" override="1"/></Element></MarkPart></Mark>"
adsm_dial.ContentString3 ""
adsm_dial.ContentString4 ""
adsm_dial.ChamferContentString ""
adsm_dial.PourContentString ""
adsm_dial.PourBreakContentString ""
adsm_dial.leader_line_type 0
adsm_dial.merge_dir 0
adsm_dial.MergeMarks 0
adsm_dial.CurrentContentTableNumber 0
adsm_dial.ForSubassMain 0
adsm_dial.ForSubassSecondary 0
adsm_dial.UseHiddenLines 0
adsm_dial.Rotation 0
adsm_dial.create_en 1
adsm_dial.for_main_en 1
adsm_dial.for_sec_en 1
adsm_dial.for_which_parts_en 1
adsm_dial.in_all_views_en 1
adsm_dial.OutOfPlane_en 1
adsm_dial.text_type_en 1
adsm_dial.text_colour_en 1
adsm_dial.frame_en 1
adsm_dial.line_colour_en 1
adsm_dial.Angle_en 1
adsm_dial.ArrowType_en 1
adsm_dial.ArrowHeight_en 1
adsm_dial.ArrowLength_en 1
adsm_dial.height_en 1
adsm_dial.content_en 1
adsm_dial.place_en 1
adsm_dial.default_size_en 1
adsm_dial.mark_nsfs_en 1
adsm_dial.use_part_end_en 1
adsm_dial.leader_line_type_en 1
adsm_dial.merge_dir_en 1
adsm_dial.MergeMarks_en 1
adsm_dial.ForSubassMain_en 1
adsm_dial.ForSubassSecondary_en 1
adsm_dial.UseHiddenLines_en 1
adsm_dial.Rotation_en 1
adsm_dial.txpl.text_placing_mode 0
adsm_dial.txpl.quarter_1 1
adsm_dial.txpl.quarter_2 2
adsm_dial.txpl.quarter_3 4
adsm_dial.txpl.quarter_4 8
adsm_dial.txpl.text_freepl_min 12.700000
adsm_dial.txpl.text_freepl_margin 9.525000
adsm_dial.txpl.text_place_en 1
adsm_dial.txpl.text_quarter_en 1
adsm_dial.txpl.text_freepl_min_en 1
adsm_dial.txpl.text_freepl_margin_en 1
adsm_dial.FontAttr.font_name "Arial"
adsm_dial.FontAttr.text_colour 153
adsm_dial.FontAttr.height 3.175000
adsm_dial.FontAttr.font_enable 1
adsm_dial.FontAttr.text_colour_enable 1
adsm_dial.FontAttr.height_enable 1
adsm_dial.FrameAttr.frame_type 1
adsm_dial.FrameAttr.line_colour 153
adsm_dial.FrameAttr.frame_enable 1
adsm_dial.FrameAttr.line_colour_enable 1
adsm_dial.UnitAttr.Unit 0
adsm_dial.UnitAttr.Precision 0
adsm_dial.UnitAttr.Format 0
adsm_dial.LocationAttributes.DesiredLocationOnPart_enable 1
adsm_dial.LocationAttributes.DesiredLocationOnPart 0
adsm_dial.LocationAttributes.LocationOnPart 0
adsm_dial.LocationAttributes.Orientation_enable 1
adsm_dial.LocationAttributes.AngleRelativeTo 0
adsm_dial.LocationAttributes.Alignment_enable 1
adsm_dial.LocationAttributes.Alignment 0
adsm_dial.LocationAttributes.PlacingFallback_enable 1
adsm_dial.LocationAttributes.PlacingFallback 0
adsm_dial.LocationAttributes.Offset_enable 1
adsm_dial.LocationAttributes.Offset 0.000000
adsm_dial.LocationAttributes.LeaderLineDesired_enable 1
adsm_dial.LocationAttributes.LeaderLineDesired 0
adsm_dial.LocationAttributes.LeaderLineInUse 0
adsm_dial.LocationAttributes.MinimumMarkScale 0.000000
adsm_dial.RebarGroupMarkAttributes.LineType 0
adsm_dial.RebarGroupMarkAttributes.Type 0
adsm_dial.RebarGroupMarkAttributes.TaggedRebarDimMarkLocation 0
adsm_dial.RebarGroupMarkAttributes.CloseRebarDimMarkToFather 0
adsm_dial.RebarGroupMarkAttributes.LineType_en 1
adsm_dial.RebarGroupMarkAttributes.Type_en 1
adsm_dial.RebarGroupMarkAttributes.TaggedRebarDimMarkLocation_en 1
adsm_dial.RebarGroupMarkAttributes.CloseRebarDimMarkToFather_en 1
